import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "LLM",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <navbar className="w-full flex items-center gap-3 h-11 bg-slate-100 ">
           <Link href={'/chat'} className="hover:text-cyan-600 transition-all">Chat</Link> 
           <Link href={'/'} className="hover:text-cyan-600 transition-all">Home</Link>
        </navbar>
        {children}
      </body>
    </html>
  );
}
